#+TITLE: Change Log
#+STARTUP: content
#+OPTIONS: H:1 num:nil author:nil creator:nil timestamp:nil toc:nil
#+TODO: ADDED CHANGED DEPRECATED REMOVED FIXED SECURITY

All notable changes to this project will be documented in this file. This
project adheres to [[https://semver.org/spec/v2.0.0.html][Semantic Versioning 2.0.0]].

* COMMENT Unreleased

** ADDED The ~vc-p4-client~ custom variable

This allows users to set a client name to use. The idea is that this lets users set the client to use for a certain directory tree, when they have multiple clients they use.

** CHANGED Enabled ~lexical-binding~

Both =vc-p4.el= and =p4-lowlevel.el= now use lexical binding instead of dynamic binding.

** ADDED ~vc-p4-login~ command

This interactive command lets you log in to Perforce when your session has expired.

** FIXED ~vc-p4-checkin~ command

~vc-p4~ should now be usable to check files into Perforce.

** FIXED Responding to the situation where a file needs to be updated

VC expects the status to be reported as ~needs-update~, not ~needs-patch~.

* 0.2.1 -- 2020-05-27
** FIXED Recognition of sub-directories of Perforce repos

   In other words, on Windows, vc-p4 now correctly recognizes sub-directories as
   part of the repository.

** CHANGED Minimum required Emacs version to 25

** FIXED vc-dir for vc-p4

   =vc-dir= has changed the function that it calls to =vc-BACKEND-dir-status-files=,
   from =vc-BACKEND-dir-status=, so now calling =vc-dir= should work again.
